### Input file for comparison of GMPEs using plotting functions in openquake.smt.comparison.compare_gmpes

[general]
imt_list = ['PGA', 'SA(0.2)', 'SA(1.0)'] # IMTs to compute attenuation curves for
max_period = 2 # Max period for response spectra (can't exceed maximum period in a specified GMPE)
minR = 0 # Min dist. used in trellis, Sammon's, clusters and matrix plots
maxR = 300 # Max dist. used in trellis, Sammon's, clusters and matrix plots
dist_type = 'repi' # Specify distance metric for trellis and response spectra
dist_list = [10, 100, 250] # Distance intervals for use in spectra plots
Nstd = 0 # Truncation for GMM sigma distribution

[site_properties] # Specify site properties (vs30 must be specified - the others are proxied if key is missing)
vs30 = 800
z1pt0 = -999  # (m) - if -999 compute from each GMM's own vs30 to z1pt0 relationship
z2pt5 = -999  # (km) - if -999 compute from each GMM's own vs30 to z2pt5 relationship
up_or_down_dip = 1 # 1 = up-dip, 0 = down-dip
volc_back_arc = false # true or false
eshm20_region = 0 # Residual attenuation cluster to use for KothaEtAl2020ESHM20

[source_properties] # Characterise EQ as finite rupture
lon = 0
lat = 0
strike = 0
dip = 45
rake = 60 # Must be provided. Strike and dip can be approximated if set to -999
mags = [5,6,7] # mags used only for trellis and response spectra
depths = [20,25,30] # depth per magnitude for trellis and response spectra
ztor = -999 # Set to -999 to NOT consider
aratio = 2 # If set to -999 the user-provided trt string will be used to assign a trt-dependent aratio
trt = -999 # Either -999 to use provided aratio OR specify a trt string to assign a trt-dependent proxy

[euclidean_analysis] # Mags/depths for Sammons maps, matrix plots and clustering (can omit if unneeded)
mag_spacing = 0.1
mags_depths = [[5, 20], [6, 20], [7, 20]] # [[mag, depth], [mag, depth], [mag, depth]] 
gmpe_labels = ['B20', 'L19', 'K1', 'K2', 'K3', 'K4', 'K5', 'CB14', 'AK14']

[models] # Specify GMMs

# Plot logic tree and individual GMPEs for below GMC logic tree config (gmc1)
[models.BooreEtAl2020]
lt_weight_gmc1 = 0.3
    
[models.LanzanoEtAl2019_RJB_OMO]
lt_weight_gmc1 = 0.40

# Default K20_ESHM20 logic tree branches considered in gmc1
[models.1-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.000862
sigma_mu_epsilon = 2.85697 
c3_epsilon = 1.72    

[models.2-KothaEtAl2020ESHM20]   
lt_weight_gmc1 = 0.067767
sigma_mu_epsilon = 1.35563
c3_epsilon = 0

[models.3-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.162742
sigma_mu_epsilon = 0
c3_epsilon = 0        

[models.4-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.067767
sigma_mu_epsilon = -1.35563
c3_epsilon = 0 

[models.5-KothaEtAl2020ESHM20]
lt_weight_gmc1 = 0.000862
sigma_mu_epsilon = -2.85697 
c3_epsilon = -1.72    
        
# Plot logic tree only for the second GMC logic tree config (gmc2)
[models.CampbellBozorgnia2014]
lt_weight_gmc2_plot_lt_only = 0.50
estimate_ztor=true

[models.AkkarEtAlRjb2014]
lt_weight_gmc2_plot_lt_only = 0.50
    
# Also specify a GMM to compute ratios of the attenuation against (GMM/baseline)
[ratios_baseline_gmm.BooreEtAl2020]

[custom_plotting]
custom_colors_flag = false # Set to true for custom colours in plots)
custom_colors_list = ['lime', 'dodgerblue', 'gold', '0.8']